"""Markdown and Comment Formatter for Code Review Agent.

Formats structured ReviewResult into a polished GitHub PR comment with badges,
tables, collapsible finding cards, and actionable remediation steps.
"""

from __future__ import annotations
from .models import ReviewResult, Finding, Verdict, Severity


def format_pr_comment(result: ReviewResult, pr_number: int | None = None) -> str:
    """Format a ReviewResult into a GitHub PR comment markdown."""
    verdict = result.verdict.lower()
    if verdict == "approve":
        badge = "![Approved](https://img.shields.io/badge/Review-APPROVED-success?style=for-the-badge)"
    elif verdict == "request_changes":
        badge = "![Changes Requested](https://img.shields.io/badge/Review-CHANGES_REQUESTED-critical?style=for-the-badge)"
    else:
        badge = "![Comment](https://img.shields.io/badge/Review-COMMENT-blue?style=for-the-badge)"

    stats = result.stats
    pr_title = f" ### 🤖 AI Code Review Summary {'#' + str(pr_number) if pr_number else ''}"

    lines = [
        f"## {badge}",
        "",
        pr_title,
        "",
        f"> {result.summary}",
        "",
        "### 📊 Review Overview",
        "",
        f"| Metric | Count |",
        f"| :--- | :--- |",
        f"| 🚨 **Critical Issues** | **{stats.critical_count}** |",
        f"| ⚠️ **High Issues** | **{stats.high_count}** |",
        f"| 🟡 **Medium Issues** | **{stats.medium_count}** |",
        f"| ℹ️ **Low / Info Issues** | **{stats.low_count}** |",
        f"| 💡 **Actionable Suggestions** | **{stats.suggestions_count}** |",
        f"| 📁 **Files Reviewed** | {stats.files_reviewed} |",
        "",
    ]

    if not result.findings:
        lines.extend([
            "### ✅ Clean Code!",
            "No significant bugs, security vulnerabilities, or code quality issues detected.",
            "",
            "---",
            "*Generated by **DeployHub AI Code Review Agent** (Multi-Agent CI/CD Platform)*",
        ])
        return "\n".join(lines)

    lines.append("### 🔍 Detailed Findings")
    lines.append("")

    # Group findings by severity
    grouped: dict[str, list[Finding]] = {
        Severity.CRITICAL.value: [],
        Severity.HIGH.value: [],
        Severity.MEDIUM.value: [],
        Severity.LOW.value: [],
        Severity.INFO.value: [],
    }
    for f in result.findings:
        sev = f.severity.lower()
        if sev in grouped:
            grouped[sev].append(f)
        else:
            grouped[Severity.INFO.value].append(f)

    for sev, findings_list in grouped.items():
        if not findings_list:
            continue
        emoji = {"critical": "🚨", "high": "⚠️", "medium": "🟡", "low": "ℹ️", "info": "💡"}.get(sev, "•")
        lines.append(f"#### {emoji} {sev.upper()} Severity ({len(findings_list)})")
        lines.append("")

        for idx, f in enumerate(findings_list, 1):
            line_str = f":L{f.line}" if f.line else ""
            rule_badge = f"`{f.rule_id}` " if f.rule_id else ""
            lines.append(f"<details><summary><b>{rule_badge}{f.file}{line_str} — {f.title}</b></summary>")
            lines.append("")
            lines.append(f"- **Category:** `{f.category}` ({f.source})")
            lines.append(f"- **Issue:** {f.description}")
            if f.code_snippet:
                lines.append("```")
                lines.append(f.code_snippet)
                lines.append("```")
            lines.append(f"- **Fix Suggestion:** {f.suggestion}")
            lines.append("")
            lines.append("</details>")
            lines.append("")

    lines.extend([
        "---",
        "*Generated by **DeployHub Multi-Agent CI/CD Platform** · Semgrep + SonarQube + Gemini Analysis*",
    ])
    return "\n".join(lines)
