import { useState, useEffect } from 'react';
import { 
  FiGitBranch, FiPlay, FiCheck, FiAlertTriangle, FiCopy, FiUploadCloud, 
  FiClock, FiCode, FiShield, FiCpu, FiLayers, FiRefreshCw, FiCheckCircle, FiXCircle 
} from 'react-icons/fi';
import { getImportedRepos, generatePipeline, pushFile, getPipelineHistory } from '../api/github';
import DashboardLayout from '../components/DashboardLayout';
import './PipelinesPage.css';

export default function PipelinesPage({ user }) {
  const [repos, setRepos] = useState([]);
  const [selectedRepo, setSelectedRepo] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [pushing, setPushing] = useState(false);
  const [pushDone, setPushDone] = useState(false);
  const [history, setHistory] = useState([]);
  const [toast, setToast] = useState(null);
  const [activeTab, setActiveTab] = useState('yaml'); // 'yaml' | 'validator' | 'planner' | 'architecture'

  useEffect(() => {
    loadRepos();
    loadHistory();
  }, []);

  async function loadRepos() {
    try {
      const data = await getImportedRepos();
      const repoList = Array.isArray(data) ? data : [];
      setRepos(repoList);

      const params = new URLSearchParams(window.location.search);
      const ownerParam = params.get('owner');
      const repoParam = params.get('repo');
      if (ownerParam && repoParam) {
        const match = repoList.find((r) => r.owner === ownerParam && r.name === repoParam);
        if (match) setSelectedRepo(match);
      }
    } catch { setRepos([]); }
  }

  async function loadHistory() {
    try {
      const data = await getPipelineHistory();
      setHistory(Array.isArray(data) ? data : []);
    } catch { setHistory([]); }
  }

  async function handleGenerate() {
    if (!selectedRepo) return;
    setGenerating(true);
    setResult(null);
    setError(null);
    setPushDone(false);
    try {
      const data = await generatePipeline(selectedRepo.owner, selectedRepo.name, selectedRepo.defaultBranch);
      setResult(data);
      if (data?.auto_pushed || data?.push_status === 'pushed') {
        setPushDone(true);
        showToast('Pipeline generated and automatically pushed to GitHub (.github/workflows/ci.yml)!', 'success');
      } else if (data?.push_error) {
        showToast(`Pipeline generated. Auto-push note: ${data.push_error}`, 'warning');
      }
      loadHistory();
    } catch (err) {
      setError(err.message || 'Pipeline generation failed');
    } finally {
      setGenerating(false);
    }
  }

  async function handlePushToGithub() {
    if (!result || !selectedRepo) return;
    setPushing(true);
    try {
      await pushFile({
        owner: selectedRepo.owner,
        repo: selectedRepo.name,
        path: result.file_path || '.github/workflows/ci.yml',
        content: result.yaml_content,
        message: 'Add CI/CD pipeline generated by DeployHub AI Pipeline Agent',
        branch: selectedRepo.defaultBranch || 'main',
      });
      setPushDone(true);
      showToast('Pipeline pushed to GitHub (.github/workflows/ci.yml)!', 'success');
    } catch (err) {
      showToast(err.message || 'Push failed', 'error');
    } finally {
      setPushing(false);
    }
  }

  function copyYaml() {
    if (result?.yaml_content) {
      navigator.clipboard.writeText(result.yaml_content);
      showToast('YAML copied to clipboard!', 'success');
    }
  }

  function showToast(message, type) {
    setToast({ message, type });
    setTimeout(() => setToast(null), 4000);
  }

  const validation = result?.validation;
  const sections = validation?.sections;
  const strategy = result?.plan_summary?.execution_strategy;
  const trace = result?.architecture_trace;

  return (
    <DashboardLayout user={user}>
      <div className="page-header animate-fade-in">
        <div>
          <h1 className="page-title">
            <FiGitBranch size={28} /> <span className="text-gradient">Pipeline Generation Agent</span>
          </h1>
          <p className="page-subtitle">
            Autonomous multi-stage CI/CD generator: Repository Analyzer → Technology Detection → Pipeline Planner → AI Generator → Triple Validator → Self-Healing Loop
          </p>
        </div>
      </div>

      {/* Repository Selector */}
      <section className="pipeline-selector glass-card animate-fade-in delay-1">
        <h3>Select Target Repository</h3>
        <div className="repo-select-grid">
          {repos.map((repo) => (
            <button
              key={repo.id}
              className={`repo-select-card ${selectedRepo?.id === repo.id ? 'selected' : ''}`}
              onClick={() => { setSelectedRepo(repo); setResult(null); setError(null); setPushDone(false); }}
              type="button"
            >
              <span className="repo-select-name">{repo.name}</span>
              <span className="repo-select-owner">{repo.owner}</span>
            </button>
          ))}
          {repos.length === 0 && (
            <p className="empty-hint">Import repositories from the Dashboard first.</p>
          )}
        </div>

        {selectedRepo && (
          <div className="pipeline-actions">
            <button className="btn btn-primary btn-lg" onClick={handleGenerate} disabled={generating} id="btn-generate-pipeline">
              {generating ? (
                <><span className="spinner" style={{width:18,height:18,borderWidth:2,borderTopColor:'white'}}></span> Generating Pipeline...</>
              ) : (
                <><FiPlay size={18} /> Run Pipeline Generation Agent</>
              )}
            </button>
          </div>
        )}
      </section>

      {/* Error */}
      {error && (
        <div className="pipeline-error glass-card animate-fade-in">
          <FiAlertTriangle size={20} />
          <span>{error}</span>
        </div>
      )}

      {/* Result */}
      {result && (
        <section className="pipeline-result animate-fade-in">
          {/* Architecture Stepper Bar */}
          <div className="pipeline-stepper glass-card">
            <div className="stepper-title">
              <FiLayers size={18} />
              <span>Pipeline Agent Architecture Execution Trace</span>
              {result.iterations_count > 1 && (
                <span className="badge-feedback-loop">
                  <FiRefreshCw size={12} className="spin-icon" /> Auto-Fix Feedback Loop ({result.iterations_count} iterations)
                </span>
              )}
              <span className="validation-time">{result.generation_time_ms}ms</span>
            </div>
            <div className="stepper-steps">
              <div className="step-node completed">
                <span className="step-num">1</span>
                <span className="step-label">Repository Analyzer</span>
              </div>
              <div className="step-arrow">→</div>
              <div className="step-node completed">
                <span className="step-num">2</span>
                <span className="step-label">Technology Detection</span>
              </div>
              <div className="step-arrow">→</div>
              <div className="step-node completed">
                <span className="step-num">3</span>
                <span className="step-label">Pipeline Planner</span>
              </div>
              <div className="step-arrow">→</div>
              <div className="step-node completed">
                <span className="step-num">4</span>
                <span className="step-label">AI Generator</span>
              </div>
              <div className="step-arrow">→</div>
              <div className="step-node completed">
                <span className="step-num">5</span>
                <span className="step-label">Pipeline Validator</span>
              </div>
              <div className="step-arrow">→</div>
              <div className={`step-node ${result.validation_passed ? 'completed success' : 'warning'}`}>
                <span className="step-num">6</span>
                <span className="step-label">Final Workflow</span>
              </div>
            </div>
          </div>

          {/* Navigation Tabs */}
          <div className="result-tabs">
            <button 
              className={`tab-btn ${activeTab === 'yaml' ? 'active' : ''}`}
              onClick={() => setActiveTab('yaml')}
            >
              <FiCode size={16} /> Generated Workflow YAML
            </button>
            <button 
              className={`tab-btn ${activeTab === 'validator' ? 'active' : ''}`}
              onClick={() => setActiveTab('validator')}
            >
              <FiShield size={16} /> Validator Report
              {validation?.valid ? (
                <span className="tab-badge-pass">PASS</span>
              ) : (
                <span className="tab-badge-fail">{validation?.errors?.length || 0}</span>
              )}
            </button>
            <button 
              className={`tab-btn ${activeTab === 'planner' ? 'active' : ''}`}
              onClick={() => setActiveTab('planner')}
            >
              <FiCpu size={16} /> Planned Stages & Strategy
            </button>
            <button 
              className={`tab-btn ${activeTab === 'architecture' ? 'active' : ''}`}
              onClick={() => setActiveTab('architecture')}
            >
              <FiLayers size={16} /> Full Architecture Trace
            </button>
          </div>

          {/* TAB 1: YAML PREVIEW */}
          {activeTab === 'yaml' && (
            <div className="pipeline-yaml glass-card animate-fade-in">
              <div className="yaml-header">
                <div className="yaml-title-group">
                  <h3>Generated Pipeline Workflow</h3>
                  <span className="file-path-badge">{result.file_path || '.github/workflows/ci.yml'}</span>
                  {(result.auto_pushed || pushDone) && (
                    <span className="badge-auto-pushed">
                      <FiCheck size={14} /> Automatically Pushed to GitHub
                    </span>
                  )}
                </div>
                <div className="yaml-actions">
                  <button className="btn btn-secondary btn-sm" onClick={copyYaml}><FiCopy size={14} /> Copy YAML</button>
                  <button className="btn btn-primary btn-sm" onClick={handlePushToGithub} disabled={pushing || pushDone || result.auto_pushed}>
                    {pushDone || result.auto_pushed ? (
                      <><FiCheck size={14} /> Pushed to GitHub</>
                    ) : pushing ? (
                      <><span className="spinner" style={{width:14,height:14,borderWidth:2}}></span> Pushing...</>
                    ) : (
                      <><FiUploadCloud size={14} /> Push to GitHub</>
                    )}
                  </button>
                </div>
              </div>
              <pre className="yaml-content"><code>{result.yaml_content}</code></pre>
            </div>
          )}

          {/* TAB 2: VALIDATOR REPORT */}
          {activeTab === 'validator' && (
            <div className="validator-panel glass-card animate-fade-in">
              <div className="validator-summary">
                <div className={`status-indicator ${validation?.valid ? 'pass' : 'fail'}`}>
                  {validation?.valid ? <FiCheckCircle size={24} /> : <FiAlertTriangle size={24} />}
                  <div>
                    <h4>{validation?.valid ? 'Validation Passed' : 'Validation Issues Detected'}</h4>
                    <p>{validation?.valid ? 'All YAML syntax, security guidelines, and schema rules satisfied.' : `${validation?.errors?.length || 0} blocking errors detected.`}</p>
                  </div>
                </div>
              </div>

              <div className="validator-grid">
                {/* 1. YAML Syntax */}
                <div className="validator-card">
                  <h5>1. YAML Syntax & Structure</h5>
                  <div className={`check-status ${sections?.yaml_syntax?.valid ? 'check-pass' : 'check-fail'}`}>
                    {sections?.yaml_syntax?.valid ? <FiCheckCircle size={16} /> : <FiXCircle size={16} />}
                    <span>{sections?.yaml_syntax?.valid ? 'Valid GitHub Actions YAML' : 'Syntax / Schema Errors'}</span>
                  </div>
                  {sections?.yaml_syntax?.errors?.length > 0 && (
                    <ul className="val-list error">
                      {sections.yaml_syntax.errors.map((e, idx) => <li key={idx}>{e}</li>)}
                    </ul>
                  )}
                </div>

                {/* 2. Security Validation */}
                <div className="validator-card">
                  <h5>2. Security Validation</h5>
                  <div className={`check-status ${sections?.security_validation?.secure ? 'check-pass' : 'check-fail'}`}>
                    {sections?.security_validation?.secure ? <FiCheckCircle size={16} /> : <FiXCircle size={16} />}
                    <span>{sections?.security_validation?.secure ? 'Secure (Least-Privilege & Pinned)' : 'Security Violations'}</span>
                  </div>
                  {sections?.security_validation?.issues?.length > 0 && (
                    <ul className="val-list error">
                      {sections.security_validation.issues.map((iss, idx) => <li key={idx}>{iss}</li>)}
                    </ul>
                  )}
                  {sections?.security_validation?.warnings?.length > 0 && (
                    <ul className="val-list warn">
                      {sections.security_validation.warnings.map((w, idx) => <li key={idx}>{w}</li>)}
                    </ul>
                  )}
                </div>

                {/* 3. Best Practice Validation */}
                <div className="validator-card">
                  <h5>3. Best Practice Validation</h5>
                  <div className={`check-status ${sections?.best_practice_validation?.passed ? 'check-pass' : 'check-warn'}`}>
                    {sections?.best_practice_validation?.passed ? <FiCheckCircle size={16} /> : <FiAlertTriangle size={16} />}
                    <span>{sections?.best_practice_validation?.passed ? 'Adheres to CI Best Practices' : 'Optimization Recommendations'}</span>
                  </div>
                  {sections?.best_practice_validation?.recommendations?.length > 0 && (
                    <ul className="val-list rec">
                      {sections.best_practice_validation.recommendations.map((rec, idx) => <li key={idx}>{rec}</li>)}
                    </ul>
                  )}
                </div>
              </div>

              {/* Feedback loop history */}
              {result.iterations_history?.length > 1 && (
                <div className="feedback-loop-history">
                  <h5><FiRefreshCw size={14} /> Self-Healing Auto-Fix History</h5>
                  <div className="iterations-timeline">
                    {result.iterations_history.map((it, i) => (
                      <div key={i} className={`timeline-entry ${it.passed ? 'pass' : 'fail'}`}>
                        <div className="timeline-badge">Iter {it.iteration || i + 1}</div>
                        <div className="timeline-info">
                          <span className="timeline-status">{it.passed ? 'Validation Passed' : `${it.errors_count || it.errors?.length || 1} Error(s) Triggered Auto-Fix Feedback Loop`}</span>
                          {it.errors?.length > 0 && (
                            <span className="timeline-detail">{it.errors.join('; ')}</span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 3: PLANNER */}
          {activeTab === 'planner' && (
            <div className="planner-panel glass-card animate-fade-in">
              <div className="planner-header">
                <h3>Pipeline Execution Strategy</h3>
                <div className="strategy-chips">
                  <span className="chip">Runner: {strategy?.runner || 'ubuntu-latest'}</span>
                  <span className="chip">Timeout: {strategy?.timeout_minutes || 30}m</span>
                  <span className="chip">Concurrency: cancel-in-progress</span>
                </div>
              </div>

              <h4>Planned CI/CD Stages ({result.plan_summary?.stage_count || 0})</h4>
              <div className="stages-grid">
                {result.plan_summary?.stages?.map((stage, idx) => (
                  <div key={idx} className="stage-card">
                    <span className="stage-index">{idx + 1}</span>
                    <span className="stage-name">{stage}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 4: ARCHITECTURE TRACE */}
          {activeTab === 'architecture' && (
            <div className="architecture-panel glass-card animate-fade-in">
              <h3>Architectural Pipeline Inspection</h3>
              <div className="trace-grid">
                <div className="trace-card">
                  <h4>1. Repository Analyzer</h4>
                  <p>Analyzed file tree and project dependencies.</p>
                  <div className="trace-stats">
                    <div><span>Manifests:</span> {trace?.repository_analyzer?.manifest_files?.join(', ') || 'None'}</div>
                    <div><span>Docker Present:</span> {trace?.repository_analyzer?.structure?.has_docker ? 'Yes' : 'No'}</div>
                    <div><span>Total Dependencies:</span> {trace?.repository_analyzer?.dependencies_count || '0'}</div>
                  </div>
                </div>

                <div className="trace-card">
                  <h4>2. Technology Detection</h4>
                  <div className="tech-tags">
                    <span className="tech-tag">Lang: {result.technology?.language || 'Unknown'}</span>
                    <span className="tech-tag">Framework: {result.technology?.framework || 'None'}</span>
                    <span className="tech-tag">Build: {result.technology?.build_tool || 'Unknown'}</span>
                    <span className="tech-tag">Test: {result.technology?.test_framework || 'None'}</span>
                  </div>
                </div>

                <div className="trace-card">
                  <h4>3. Pipeline Planner</h4>
                  <p>Calculated optimal sequence of execution stages and safety limits.</p>
                  <div><span>Stages Planned:</span> {trace?.pipeline_planner?.stages?.length || 0}</div>
                </div>

                <div className="trace-card">
                  <h4>4 & 5. Generator & Validator Loop</h4>
                  <div><span>Total Iterations:</span> {result.iterations_count}</div>
                  <div><span>Validation Status:</span> {result.validation_passed ? 'PASSED' : 'WARNINGS'}</div>
                </div>
              </div>
            </div>
          )}
        </section>
      )}

      {/* History */}
      {history.length > 0 && (
        <section className="pipeline-history glass-card animate-fade-in delay-2">
          <h3><FiClock size={18} /> Generation History</h3>
          <div className="history-list">
            {history.slice(0, 10).map((run) => (
              <div key={run.id} className="history-item">
                <div className={`history-status status-${run.status}`}>{run.status}</div>
                <div className="history-info">
                  <span className="history-repo">{run.owner}/{run.repoName}</span>
                  <span className="history-time">{new Date(run.createdAt).toLocaleString()}</span>
                </div>
                <span className="history-ms">{run.generationTimeMs}ms</span>
              </div>
            ))}
          </div>
        </section>
      )}

      {toast && <div className={`toast toast-${toast.type}`}>{toast.message}</div>}
    </DashboardLayout>
  );
}
